# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker build \
          -t actionspkgstest:latest .
    - name: Tag and Push
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u jpadams --password-stdin
        docker tag actionspkgstest:latest docker.pkg.github.com/jpadams/actionspkgs/actionspkgstest:latest
        docker push docker.pkg.github.com/jpadams/actionspkgs/actionspkgstest:latest
    - name: Remove local image and Pull from GH Packages
      run: |
        echo "#### Logging in with GITHUB_TOKEN"
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u jpadams --password-stdin
        
        echo "#### Checking for actionspkgstest images"
        echo "======================"
        { docker images; echo "no OTHER actionspkgstest IMAGES"; } | grep actionspkgstest | sort -d
        echo "======================"
        
        echo "#### Removing local actionspkgstest images"
        docker rmi actionspkgstest:latest
        docker rmi docker.pkg.github.com/jpadams/actionspkgs/actionspkgstest:latest
        
        echo "#### Checking for actionspkgstest images"
        echo "======================"
        { docker images; echo "no OTHER actionspkgstest IMAGES"; } | grep actionspkgstest | sort -d
        echo "======================"
        
        echo "#### Pulling actionspkgstest image back down from GH Packages"
        docker pull docker.pkg.github.com/jpadams/actionspkgs/actionspkgstest:latest

        echo "#### Checking for actionspkgstest images"
        echo "======================"
        { docker images; echo "no OTHER actionspkgstest IMAGES"; } | grep actionspkgstest | sort -d
        echo "======================"
